# This Cloud Build file performs the following actions:
# 1. Generates a short-lived access token for the specified service account.
# 2. Builds a Docker image from the current directory.
# 3. Runs an external scanner image, passing all necessary variables and the
#    GCP access token as environment variables to the running container.

steps:
  # 1. Generate Access Token and save it to the shared /workspace
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Generate Token'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Starting token generation for the service account..."
        # gcloud auth print-access-token gets a short-lived token
        gcloud auth print-access-token > /workspace/gcp_token.txt
        if [ $? -ne 0 ]; then
          echo "Failed to generate token." >&2
          exit 1
        fi
        echo "Token generated successfully."

  # 2. Build the Docker Image from source
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Image'
    args:
      - 'build'
      - '-t'
      - '${_IMAGE_NAME_TO_SCAN}:${_IMAGE_TAG}'
      - '.'

  # 3. Image Analysis - Run the scanner image as a container
  # The scanner image runs the script that executes your API call using the passed environment variables.
  - id: 'Image-Analysis'
    # This is the image that contains your analysis script and curl command
    name: '$_SCANNER_IMAGE'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Starting image analysis and API submission..."
        
        # Pass the access token directly by reading the file content
        ACCESS_TOKEN_VALUE=$(cat /workspace/gcp_token.txt)
        
        exit_code=0
        docker run --rm \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v /workspace:/workspace \
          -e GCP_PROJECT_ID="$PROJECT_ID" \
          -e ORGANIZATION_ID="$_ORGANIZATION_ID" \
          -e IMAGE_NAME="$_IMAGE_NAME_TO_SCAN" \
          -e IMAGE_TAG="$_IMAGE_TAG" \
          -e IMAGE_DIGEST="$_IMAGE_DIGEST" \
          -e API_ENDPOINT="$_API_ENDPOINT" \
          # CORRECTLY PASSING THE ACCESS TOKEN TO THE DOCKER CONTAINER
          -e GCP_ACCESS_TOKEN="$ACCESS_TOKEN_VALUE" \
          "$_SCANNER_IMAGE" || exit_code=$?
          
        if [ $exit_code -ne 0 ]; then
          echo "❌ Image analysis failed with exit code $exit_code." >&2
          exit 1
        fi
        echo "✅ Image analysis completed successfully."

# ----------------------------------------------------------------------
# GLOBAL CONFIGURATION
# ----------------------------------------------------------------------

substitutions:
  # User-defined variables
  _IMAGE_NAME_TO_SCAN: 'alpine'
  _ORGANIZATION_ID: '864375476167'
  _SCANNER_IMAGE: 'gcr.io/ci-plugin/cloud-build-integration:latest'
  _IMAGE_TAG: 'latest'
  _IMAGE_DIGEST: 'sha256:b0c6491f5ba0dff4c919008f5ab48db97315676136c21796e41fb6326e88d02a'
  _API_ENDPOINT: 'us-west1-gkehub.googleapis.com' # Replace with your actual endpoint

# The service account must have permissions to generate its own token and call the target API.
serviceAccount: "projects/ci-plugin/serviceAccounts/696023462194-compute@developer.gserviceaccount.com"

options:
  logging: CLOUD_LOGGING_ONLY
