# cloudbuild.yaml

steps:
  # 1. Generate Access Token and save it to the shared /workspace
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Generate Token'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Starting token generation for the service account..."
        # gcloud auth print-access-token gets a short-lived token
        gcloud auth print-access-token > /workspace/gcp_token.txt
        if [ $? -ne 0 ]; then
          echo "Failed to generate token." >&2
          exit 1
        fi
        echo "Token generated successfully."

  # 2. Build the Docker Image from source
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Image'
    args:
      - 'build'
      - '-t'
      - '${_IMAGE_NAME_TO_SCAN}:${_IMAGE_TAG}'
      - '.'

  # 3. Image Analysis - Run the scanner image as a container
  - id: 'Image-Analysis'
    name: '$_SCANNER_IMAGE'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Starting image analysis and API submission..."
        
        # 1. Read the token from the file into a shell variable
        ACCESS_TOKEN_VALUE=$(cat /workspace/gcp_token.txt)
        
        # 2. Set this shell variable as an environment variable for the DOCKER CONTAINER
        # NOTE: We use $$ to prevent Cloud Build from trying to substitute it here.
        exit_code=0
        docker run --rm \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v /workspace:/workspace \
          -e GCP_PROJECT_ID="$PROJECT_ID" \
          -e ORGANIZATION_ID="$_ORGANIZATION_ID" \
          -e IMAGE_NAME="$_IMAGE_NAME_TO_SCAN" \
          -e IMAGE_TAG="$_IMAGE_TAG" \
          -e IMAGE_DIGEST="$_IMAGE_DIGEST" \
          -e API_ENDPOINT="$_API_ENDPOINT" \
          # THIS IS THE CRITICAL LINE: Use shell variable expansion
          -e GCP_ACCESS_TOKEN="$ACCESS_TOKEN_VALUE" \
          "$_SCANNER_IMAGE" || exit_code=$?
          
        if [ $exit_code -ne 0 ]; then
          echo "❌ Image analysis failed with exit code $exit_code." >&2
          exit 1
        fi
        echo "✅ Image analysis completed successfully."

# ----------------------------------------------------------------------
# GLOBAL CONFIGURATION
# ----------------------------------------------------------------------

substitutions:
  # User-defined variables (MUST start with an underscore)
  _IMAGE_NAME_TO_SCAN: 'alpine'
  _ORGANIZATION_ID: '864375476167'
  _SCANNER_IMAGE: 'gcr.io/ci-plugin/cloud-build-integration:latest'
  _IMAGE_TAG: 'latest'
  _IMAGE_DIGEST: 'sha256:b0c6491f5ba0dff4c919008f5ab48db97315676136c21796e41fb6326e88d02a'
  _API_ENDPOINT: 'us-west1-gkehub.googleapis.com' 

serviceAccount: "projects/ci-plugin/serviceAccounts/696023462194-compute@developer.gserviceaccount.com"

options:
  logging: CLOUD_LOGGING_ONLY
