# A workflow to connect to GCP
name: Connect to GCP

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# The job to run
jobs:
  build-and-connect:
    # The type of virtual machine the job will run on
    runs-on: ubuntu-latest

    # The steps to execute
    steps:
      # 1. Checkout the repository's code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Authenticate to Google Cloud
      - name: Authenticate to GCP
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # 3. Setup the gcloud CLI
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      # 4. Run a gcloud command to verify authentication
      #    This command lists all your GCS buckets.
      - name: List GCS Buckets
        run: 'gcloud storage ls'
